# Usa una imagen base de Node.js específica
FROM node:24.14.0

# Establece el directorio de trabajo en la imagen
WORKDIR /usr/src/app

# Copia el package.json y package-lock.json (o yarn.lock) al contenedor
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 3000

# Compila la aplicación
RUN npm run build

# Comando para ejecutar la aplicación
CMD ["npm", "run", "start:prod"]